language: objective-c

before_script:
  - brew update
  - brew uninstall xctool
  - brew install xctool
  
script: 
  - xctool -project SDColor.xcodeproj -scheme SDColor -sdk iphonesimulator build test ONLY_ACTIVE_ARCH=NO
