language: objective-c

before_script:
  - open -a iPhone\ Simulator
  
script: 
  - xctool -project SDColor.xcodeproj -scheme SDColor -sdk iphonesimulator build test -freshInstall -freshSimulator ONLY_ACTIVE_ARCH=NO
